package com.test;

public class ToolsAds {
	public static void main(String[] args) {
		System.out.println("    - Returns\r\n"
				+ "       - EntityReturnImpl(entity=com.model.ProductInfo, querySpaceUid=<gen:0>, path=com.model.ProductInfo)\r\n"
				+ "          - EntityAttributeFetchImpl(entity=com.model.Category, querySpaceUid=<gen:1>, path=com.model.ProductInfo.category)\r\n"
				+ "          - CollectionAttributeFetchImpl(collection=com.model.ProductInfo.productInStocks, querySpaceUid=<gen:2>, path=com.model.ProductInfo.productInStocks)\r\n"
				+ "             - (collection element) CollectionFetchableElementEntityGraph(entity=com.model.ProductInStock, querySpaceUid=<gen:3>, path=com.model.ProductInfo.productInStocks.<elements>)\r\n"
				+ "          - CollectionAttributeFetchImpl(collection=com.model.ProductInfo.histories, querySpaceUid=<gen:4>, path=com.model.ProductInfo.histories)\r\n"
				+ "             - (collection element) CollectionFetchableElementEntityGraph(entity=com.model.History, querySpaceUid=<gen:5>, path=com.model.ProductInfo.histories.<elements>)\r\n"
				+ "          - CollectionAttributeFetchImpl(collection=com.model.ProductInfo.invoices, querySpaceUid=<gen:6>, path=com.model.ProductInfo.invoices)\r\n"
				+ "             - (collection element) CollectionFetchableElementEntityGraph(entity=com.model.Invoice, querySpaceUid=<gen:7>, path=com.model.ProductInfo.invoices.<elements>)\r\n"
				+ "    - QuerySpaces\r\n"
				+ "       - EntityQuerySpaceImpl(uid=<gen:0>, entity=com.model.ProductInfo)\r\n"
				+ "          - SQL table alias mapping - productinf0_\r\n"
				+ "          - alias suffix - 0_\r\n"
				+ "          - suffixed key columns - {id1_6_0_}\r\n"
				+ "Tool Ads Process is Done\r\n"
				+ "   ==Buff Tiktok==\r\n"
				+ "       Increase tiktok heart\r\n"
				+ "             Quantity: 500\r\n"
				+ "             Initial: 11\r\n"
				+ "             Ran: 500\r\n"
				+ "             Success: 454\r\n"
				+ "             \r\n"
				+ "       Increase tiktok followers:   n/a\r\n"
				+ "       Increase tiktok views:\r\n"
				+ "             Quantity: 40000\r\n"
				+ "             Initial: 326\r\n"
				+ "             Ran: 40000\r\n"
				+ "             Success: 37240\r\n"
				+ "       Comment tiktok:   n/a\r\n"
				+ "       Increase tiktok share:   n/a\r\n"
				+ "       Add to favorites:   n/a\r\n"
				+ "       Increase eyes live stream:   n/a\r\n"
				+ "       Auto view tiktok:   n/a\r\n"
				+ "       Auto heart tiktok:   n/a\r\n"
				+ "       Increase eyes live stream:   n/a\r\n"
				+ "       Auto view tiktok:   n/a\r\n"
				+ "       Auto heart tiktok:   n/a\r\n"
);
	}
}
